server:
  port: 9090

spring:
  profiles:
    active: default,ci,test

  jpa:
    hibernate:
      ddl-auto: none
      properties:
        hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
        hibernate.format_sql: true
    properties:
      hibernate.format_sql: true
    sql.init.mode: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${STATS_DATASOURCE_URL:jdbc:postgresql://localhost:5432/stats}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:password}

  config:
    activate:
      on-profile: default,ci,test

  h2:
    console:
      enabled: true

---

spring:
  profiles:
    active: default,ci,test

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:stats
    username: test
    password: test
