server:
  port: 8080
stats-server:
  url: http://localhost:9090
spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  main:
    banner-mode: off
datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/ewm-db
  username: ewm
  password: ewm
logging:
  level:
    org.springframework.orm.jpa: INFO
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
---
spring:
  config:
    activate:
      on-profile: ci,test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:ewm-db
    username: test
    password: test